repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-toml
    -   id: no-commit-to-branch
        args: [-b, master]

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        name: black
        entry: black
        require_serial: true
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        exclude: ^docs/conf.py

  - repo: https://github.com/yaq-project/yaq-traits
    rev: v2021.4.0
    hooks:
      - id: yaq-traits-check
      - id: yaq-traits-compose

